[package]
name = "gst-custom-webrtc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
async-std = "1"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
rand = "0.8"
async-tungstenite = { version = "0.21", features = ["async-std-runtime", "async-native-tls"] }
gst = { package = "gstreamer", version = "0.20" }
gst-rtp = { package = "gstreamer-rtp", version = "0.20", features = ["v1_20"] }
gst-webrtc = { package = "gstreamer-webrtc", version = "0.20" }
gst-sdp = { package = "gstreamer-sdp", version = "0.20" }
serde = "1"
serde_derive = "1"
serde_json = "1"

